[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "freetype", "harfbuzz", "ca-certificates", "ttf-dejavu"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps --omit=dev"]

[phases.build]
cmds = []

[start]
cmd = "node server.js"
