import React from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { ArrowLeft, Flask } from '@phosphor-icons/react';

const S = {
  h2: {
    fontFamily: "'Manrope', sans-serif",
    fontWeight: 800,
    fontSize: '1.125rem',
    color: '#00685f',
    margin: '2rem 0 0.625rem',
    letterSpacing: '-0.2px',
  } as React.CSSProperties,
  h3: {
    fontFamily: "'Manrope', sans-serif",
    fontWeight: 700,
    fontSize: '0.9375rem',
    color: 'var(--text-primary)',
    margin: '1.25rem 0 0.375rem',
  } as React.CSSProperties,
  p: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.9375rem',
    color: 'var(--text-secondary)',
    lineHeight: 1.7,
    margin: '0 0 0.75rem',
  } as React.CSSProperties,
  li: {
    fontFamily: "'Inter', sans-serif",
    fontSize: '0.9375rem',
    color: 'var(--text-secondary)',
    lineHeight: 1.7,
    marginBottom: '0.375rem',
  } as React.CSSProperties,
};

const EVIDENCE_TIERS = [
  {
    label: 'Strong',
    color: '#00685f',
    bg: '#e6f4f2',
    description:
      'Multiple large randomised controlled trials (RCTs) in healthy humans, with consistent results across independent research groups. Meta-analyses and systematic reviews available.',
  },
  {
    label: 'Moderate',
    color: '#2563eb',
    bg: '#eff6ff',
    description:
      'At least a handful of human RCTs or well-designed controlled studies, but some heterogeneity in outcomes, smaller sample sizes, or limited independent replication.',
  },
  {
    label: 'Emerging',
    color: '#d97706',
    bg: '#fffbeb',
    description:
      'Promising early-phase human studies or mechanistic evidence, but not yet confirmed by large independent trials. Worth watching but conclusions are preliminary.',
  },
  {
    label: 'Anecdotal',
    color: '#6d7a77',
    bg: 'var(--bg-hover)',
    description:
      'Limited or no controlled human trials. Evidence is largely animal-based, in-vitro, or self-reported. Use with caution; effects in humans are unproven.',
  },
];

export default function MethodologyPage() {
  const navigate = useNavigate();

  return (
    <div style={{ background: 'var(--bg-page)', minHeight: '100vh', paddingTop: '80px' }}>
      <div style={{ maxWidth: '760px', margin: '0 auto', padding: '2rem 1.25rem 4rem' }}>
        {/* Back */}
        <button
          onClick={() => navigate(-1)}
          style={{
            display: 'flex', alignItems: 'center', gap: '0.375rem',
            background: 'transparent', border: 'none', padding: '0.25rem 0',
            marginBottom: '1.5rem', color: 'var(--text-secondary)', cursor: 'pointer',
            fontFamily: "'Inter', sans-serif", fontWeight: 600, fontSize: '0.875rem',
          }}
        >
          <ArrowLeft size={16} />
          Back
        </button>

        {/* Hero */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.5rem' }}>
          <Flask size={28} color="#00685f" weight="fill" />
          <h1 style={{ fontFamily: "'Manrope', sans-serif", fontWeight: 800, fontSize: '1.75rem', color: 'var(--text-primary)', margin: 0, letterSpacing: '-0.5px' }}>
            How We Grade Evidence
          </h1>
        </div>
        <p style={{ ...S.p, color: 'var(--text-muted)', marginBottom: '2rem', fontSize: '1rem' }}>
          Our methodology for sourcing, evaluating, and presenting supplement research.
        </p>

        <div style={{ background: 'var(--bg-surface)', borderRadius: '16px', padding: '0.25rem 1.75rem 1.5rem', boxShadow: '0 1px 4px rgba(0,0,0,0.06)', marginBottom: '1rem' }}>

          <h2 style={S.h2}>Our Sources</h2>
          <p style={S.p}>
            All supplement information on SupplementScanner is grounded in peer-reviewed human research indexed on{' '}
            <a href="https://pubmed.ncbi.nlm.nih.gov/" target="_blank" rel="noopener noreferrer" style={{ color: '#00685f', fontWeight: 600 }}>PubMed</a>
            {' '}— the US National Library of Medicine's public research database containing over 36 million citations. We do not rely on manufacturer claims, self-reported data, or non-indexed journals.
          </p>
          <p style={S.p}>
            Deep-dive content is generated by an AI model (Anthropic Claude) trained on scientific literature, then cross-referenced against PubMed IDs to surface citations you can verify yourself. Every key study card links directly to its PubMed entry.
          </p>

          <h2 style={S.h2}>Evidence Tiers</h2>
          <p style={S.p}>
            Each supplement in our encyclopedia carries an evidence tier based on the quantity and quality of available human clinical research.
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.625rem', marginBottom: '0.75rem' }}>
            {EVIDENCE_TIERS.map(tier => (
              <div key={tier.label} style={{
                display: 'flex', alignItems: 'flex-start', gap: '1rem',
                background: tier.bg,
                border: `1px solid ${tier.color}30`,
                borderRadius: '12px',
                padding: '0.875rem 1rem',
              }}>
                <span style={{
                  background: tier.color, color: '#fff',
                  borderRadius: '999px', padding: '0.1875rem 0.625rem',
                  fontSize: '0.75rem', fontWeight: 700,
                  fontFamily: "'Inter', sans-serif", whiteSpace: 'nowrap', flexShrink: 0, marginTop: '2px',
                }}>
                  {tier.label}
                </span>
                <p style={{ ...S.p, margin: 0 }}>{tier.description}</p>
              </div>
            ))}
          </div>

          <h2 style={S.h2}>Study Count</h2>
          <p style={S.p}>
            The study count shown on each supplement page is a conservative estimate of peer-reviewed <strong>human clinical trials</strong> (RCTs and controlled studies) that directly investigated the supplement. We exclude:
          </p>
          <ul style={{ margin: '0 0 0.75rem', paddingLeft: '1.5rem' }}>
            <li style={S.li}>Animal studies</li>
            <li style={S.li}>In-vitro (cell culture) experiments</li>
            <li style={S.li}>Observational cohort studies and surveys</li>
            <li style={S.li}>Case reports</li>
          </ul>
          <p style={S.p}>
            When in doubt, we round down. A supplement with a count of 12 may have far more total publications — but 12 is the number we're confident crossed the bar for controlled human evidence.
          </p>

          <h2 style={S.h2}>PubMed Citations</h2>
          <p style={S.p}>
            Key study cards on each deep-dive page display the paper's PubMed ID (PMID), year, participant count, and a plain-English summary of the key finding. Clicking any card opens the original abstract on PubMed, where you can read the full citation and access the paper.
          </p>
          <p style={S.p}>
            We only include citations we are highly confident correspond to real, published papers. If a study cannot be verified with a real PMID, we omit it rather than cite it inaccurately.
          </p>

          <h2 style={S.h2}>What We Don't Do</h2>
          <ul style={{ margin: '0 0 0.75rem', paddingLeft: '1.5rem' }}>
            <li style={S.li}>We do not accept sponsored content or manufacturer-provided data as evidence.</li>
            <li style={S.li}>We do not make medical claims or personalised health recommendations.</li>
            <li style={S.li}>We do not inflate study counts to make a supplement appear better-researched than it is.</li>
            <li style={S.li}>We do not hide negative findings or safety cautions.</li>
          </ul>

          <h2 style={S.h2}>Limitations</h2>
          <p style={S.p}>
            AI-generated summaries can contain errors. The underlying model is trained on data with a knowledge cutoff, meaning very recent publications may not be reflected. Deep-dive content is cached for 30 days before being regenerated.
          </p>
          <p style={S.p}>
            SupplementScanner is an educational reference tool, not a substitute for medical advice. Always consult a qualified healthcare professional before starting or stopping any supplement.
          </p>

          <h2 style={S.h2}>Questions or Corrections</h2>
          <p style={{ ...S.p, margin: 0 }}>
            If you spot an inaccurate citation or believe a tier rating is incorrect, email us at{' '}
            <a href="mailto:supplementscanner.io@gmail.com" style={{ color: '#00685f', fontWeight: 600 }}>supplementscanner.io@gmail.com</a>.
            We take accuracy seriously and will review every report.
          </p>
        </div>

        {/* Footer nav */}
        <div style={{ display: 'flex', gap: '1.25rem', justifyContent: 'center', marginTop: '1.5rem' }}>
          <Link to="/privacy" style={{ fontFamily: "'Inter', sans-serif", fontSize: '0.8125rem', color: 'var(--text-secondary)', textDecoration: 'none', fontWeight: 500 }}>
            Privacy & Cookies
          </Link>
          <Link to="/terms" style={{ fontFamily: "'Inter', sans-serif", fontSize: '0.8125rem', color: 'var(--text-secondary)', textDecoration: 'none', fontWeight: 500 }}>
            Terms of Service
          </Link>
        </div>
      </div>
    </div>
  );
}
