import AsyncStorage from '@react-native-async-storage/async-storage';
import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';

const SAF_DIR_KEY = 'deepDiveDownloadDirUri';
const DOWNLOADED_SLUGS_KEY = 'downloadedDeepDiveSlugs';

export async function getDownloadedSlugs(): Promise<string[]> {
  const raw = await AsyncStorage.getItem(DOWNLOADED_SLUGS_KEY);
  return raw ? JSON.parse(raw) : [];
}

async function markSlugDownloaded(slug: string) {
  const slugs = await getDownloadedSlugs();
  if (slugs.includes(slug)) return;
  await AsyncStorage.setItem(DOWNLOADED_SLUGS_KEY, JSON.stringify([...slugs, slug]));
}

interface DosingInfo { low: string; standard: string; high: string; timing: string }
interface FormInfo { name: string; bioavailability: string; notes: string }
interface SynergyInfo { supplement: string; reason: string }
export interface DeepDiveContent {
  whatItIs: string;
  howItWorks: string;
  dosing: DosingInfo;
  forms: FormInfo[];
  synergies: SynergyInfo[];
  cautions: string[];
}

function esc(s: string) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function buildHtml(supplementName: string, content: DeepDiveContent): string {
  const forms = (content.forms ?? [])
    .map(f => `<li><strong>${esc(f.name)}</strong> — ${esc(f.bioavailability)} bioavailability. ${esc(f.notes)}</li>`)
    .join('');
  const synergies = (content.synergies ?? [])
    .map(s => `<li><strong>+ ${esc(s.supplement)}</strong> — ${esc(s.reason)}</li>`)
    .join('');
  const cautions = (content.cautions ?? []).map(c => `<li>${esc(c)}</li>`).join('');

  return `
    <html>
      <head><meta charset="utf-8" /></head>
      <body style="font-family: -apple-system, Helvetica, Arial, sans-serif; color: #171d1c; padding: 24px;">
        <h1 style="color: #00685f; margin-bottom: 4px;">${esc(supplementName)}</h1>
        <p style="color: #6d7a77; margin-top: 0;">Research Deep Dive</p>

        <h2>What It Is</h2>
        <p>${esc(content.whatItIs ?? '')}</p>

        <h2>How It Works</h2>
        <p>${esc(content.howItWorks ?? '')}</p>

        ${content.dosing ? `
        <h2>Dosing Protocol</h2>
        <table style="width: 100%; border-collapse: collapse;">
          <tr><td style="padding: 4px 0;"><strong>Conservative</strong></td><td>${esc(content.dosing.low ?? '')}</td></tr>
          <tr><td style="padding: 4px 0;"><strong>Standard</strong></td><td>${esc(content.dosing.standard ?? '')}</td></tr>
          <tr><td style="padding: 4px 0;"><strong>High / Loading</strong></td><td>${esc(content.dosing.high ?? '')}</td></tr>
        </table>
        ${content.dosing.timing ? `<p style="color: #00685f;"><em>${esc(content.dosing.timing)}</em></p>` : ''}
        ` : ''}

        ${forms ? `<h2>Forms &amp; Bioavailability</h2><ul>${forms}</ul>` : ''}
        ${synergies ? `<h2>Synergies</h2><ul>${synergies}</ul>` : ''}
        ${cautions ? `<h2>Cautions &amp; Interactions</h2><ul>${cautions}</ul>` : ''}

        <hr style="margin-top: 32px; border: none; border-top: 1px solid #e4e9e7;" />
        <p style="color: #6d7a77; font-size: 12px;">Generated by SupplementScanner. Not medical advice.</p>
      </body>
    </html>
  `;
}

function fileNameFor(supplementName: string): string {
  const slug = supplementName.trim().replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '');
  return `${slug || 'supplement'}-deep-dive.pdf`;
}

async function saveToAndroidDownloads(uri: string, fileName: string): Promise<boolean> {
  const { StorageAccessFramework } = FileSystem;
  let dirUri = await AsyncStorage.getItem(SAF_DIR_KEY);

  if (!dirUri) {
    const permissions = await StorageAccessFramework.requestDirectoryPermissionsAsync();
    if (!permissions.granted) return false;
    dirUri = permissions.directoryUri;
    await AsyncStorage.setItem(SAF_DIR_KEY, dirUri);
  }

  const base64 = await FileSystem.readAsStringAsync(uri, { encoding: FileSystem.EncodingType.Base64 });

  try {
    const destUri = await StorageAccessFramework.createFileAsync(dirUri, fileName, 'application/pdf');
    await FileSystem.writeAsStringAsync(destUri, base64, { encoding: FileSystem.EncodingType.Base64 });
    return true;
  } catch {
    // Previously granted folder is no longer valid (e.g. permission revoked) — forget it and retry once.
    await AsyncStorage.removeItem(SAF_DIR_KEY);
    const permissions = await StorageAccessFramework.requestDirectoryPermissionsAsync();
    if (!permissions.granted) return false;
    await AsyncStorage.setItem(SAF_DIR_KEY, permissions.directoryUri);
    const destUri = await StorageAccessFramework.createFileAsync(permissions.directoryUri, fileName, 'application/pdf');
    await FileSystem.writeAsStringAsync(destUri, base64, { encoding: FileSystem.EncodingType.Base64 });
    return true;
  }
}

export type DeepDiveExportResult = 'downloaded' | 'shared' | 'cancelled';

/**
 * Saves the deep dive as a PDF to a user-picked folder on Android (via Storage Access
 * Framework, prompted once and reused after). iOS has no equivalent "Downloads" location,
 * so it falls back to the share sheet, which is the standard way to save into Files there.
 */
export async function downloadDeepDivePdf(
  slug: string,
  supplementName: string,
  content: DeepDiveContent
): Promise<DeepDiveExportResult> {
  const html = buildHtml(supplementName, content);
  const { uri } = await Print.printToFileAsync({ html });
  const fileName = fileNameFor(supplementName);

  if (Platform.OS === 'android') {
    const saved = await saveToAndroidDownloads(uri, fileName);
    if (saved) {
      await markSlugDownloaded(slug);
      return 'downloaded';
    }
  }

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: `${supplementName} Deep Dive`,
      UTI: 'com.adobe.pdf',
    });
    await markSlugDownloaded(slug);
    return 'shared';
  }

  return 'cancelled';
}
