// Map slug → PubMed term for the substance itself (title/abstract), used to count how much
// supplementation research exists. Deliberately broader than the RAG search terms in
// ingest-pubmed.js, which are tuned for retrieving relevant abstracts, not for counting.
export const SUBSTANCE_TERMS = {
  'creatine-monohydrate':  'creatine[tiab]',
  'caffeine':              'caffeine[tiab]',
  'beta-alanine':          '"beta-alanine"[tiab]',
  'citrulline-malate':     'citrulline[tiab]',
  'betaine-anhydrous':     'betaine[tiab]',
  'hmb':                   '"beta-hydroxy-beta-methylbutyrate"[tiab] OR hydroxymethylbutyrate[tiab] OR HMB[tiab]',
  'sodium-bicarbonate':    '"sodium bicarbonate"[tiab]',
  'magnesium-glycinate':   'magnesium[tiab]',
  'magnesium-malate':      'magnesium[tiab]',
  'magnesium-l-threonate': '"magnesium threonate"[tiab] OR "magnesium L-threonate"[tiab]',
  'melatonin':             'melatonin[tiab]',
  'l-theanine':            'theanine[tiab]',
  'ashwagandha':           'ashwagandha[tiab] OR "withania somnifera"[tiab]',
  'glycine':               'glycine[tiab]',
  'lions-mane':            '"hericium erinaceus"[tiab] OR "lions mane"[tiab]',
  'bacopa-monnieri':       'bacopa[tiab]',
  'alpha-gpc':             '"alpha-GPC"[tiab] OR glycerophosphocholine[tiab] OR "choline alfoscerate"[tiab]',
  'rhodiola-rosea':        'rhodiola[tiab]',
  'panax-ginseng':         'ginseng[tiab]',
  'phosphatidylserine':    'phosphatidylserine[tiab]',
  'tart-cherry':           '"tart cherry"[tiab] OR Montmorency[tiab]',
  'omega-3':               '"omega-3"[tiab] OR "n-3 fatty acids"[tiab] OR "fish oil"[tiab]',
  'fish-oil':              '"fish oil"[tiab] OR "omega-3"[tiab] OR "eicosapentaenoic acid"[tiab] OR "docosahexaenoic acid"[tiab]',
  'collagen-peptides':     'collagen[tiab] AND (peptide*[tiab] OR hydrolys*[tiab])',
  'curcumin':              'curcumin[tiab] OR turmeric[tiab]',
  'glutamine':             'glutamine[tiab]',
  'vitamin-d3-k2':         '("vitamin D"[tiab] OR cholecalciferol[tiab]) AND ("vitamin K"[tiab] OR menaquinone*[tiab])',
  'vitamin-d3':            '"vitamin D"[tiab] OR cholecalciferol[tiab]',
  'vitamin-k2':            '"vitamin K2"[tiab] OR menaquinone*[tiab]',
  'zinc-bisglycinate':     'zinc[tiab]',
  'probiotics':            'probiotic*[tiab]',
  'vitamin-c':             '"vitamin C"[tiab] OR "ascorbic acid"[tiab]',
  'berberine':             'berberine[tiab]',
  'coq10':                 '"coenzyme Q10"[tiab] OR CoQ10[tiab] OR ubiquinone[tiab]',
  'ubiquinol':             'ubiquinol[tiab]',
  'taurine':               'taurine[tiab]',
  '5-htp':                 '"5-hydroxytryptophan"[tiab] OR "5-HTP"[tiab]',
  'valerian-root':         'valerian*[tiab]',
  'alcar':                 '"acetyl-L-carnitine"[tiab] OR acetylcarnitine[tiab]',
  'l-carnitine':           'carnitine[tiab]',
  'citicoline':            'citicoline[tiab] OR "CDP-choline"[tiab]',
  'ginkgo-biloba':         'ginkgo[tiab]',
  'nac':                   '"N-acetylcysteine"[tiab] OR acetylcysteine[tiab]',
  'msm':                   'methylsulfonylmethane[tiab]',
  'spirulina':             'spirulina[tiab] OR arthrospira[tiab]',
  'nmn':                   '"nicotinamide mononucleotide"[tiab]',
  'quercetin':             'quercetin[tiab]',
  'vitamin-b12':           '"vitamin B12"[tiab] OR cobalamin[tiab] OR cyanocobalamin[tiab] OR methylcobalamin[tiab]',
  'resveratrol':           'resveratrol[tiab]',
  'selenium':              'selenium[tiab]',
  'whey-protein':          'whey[tiab]',
  'l-arginine':            'arginine[tiab]',
  'yohimbine':             'yohimbine[tiab]',
  'kava':                  'kava[tiab] OR kavalactone*[tiab]',
  'passionflower':         'passiflora[tiab] OR passionflower[tiab]',
  'holy-basil':            '"ocimum sanctum"[tiab] OR "ocimum tenuiflorum"[tiab] OR tulsi[tiab] OR "holy basil"[tiab]',
  'l-tyrosine':            'tyrosine[tiab]',
  'pqq':                   '"pyrroloquinoline quinone"[tiab]',
  'nadh':                  'NADH[tiab]',
  'cla':                   '"conjugated linoleic acid"[tiab]',
  'colostrum':             'colostrum[tiab]',
  'forskolin':             'forskolin[tiab] OR "coleus forskohlii"[tiab]',
  'shilajit':              'shilajit[tiab]',
  'multivitamin':          'multivitamin*[tiab] OR "multiple micronutrient"[tiab]',
  'calcium':               'calcium[tiab]',
  'potassium':             'potassium[tiab]',
  'vitamin-b6':            '"vitamin B6"[tiab] OR pyridoxine[tiab]',
  'niacin':                'niacin[tiab] OR "nicotinic acid"[tiab]',
  'thiamine':              'thiamine[tiab] OR "vitamin B1"[tiab]',
  'riboflavin':            'riboflavin[tiab] OR "vitamin B2"[tiab]',
  'pantothenic-acid':      '"pantothenic acid"[tiab] OR pantothenate[tiab]',
  'copper':                'copper[tiab]',
  'manganese':             'manganese[tiab]',
  'boron':                 'boron[tiab]',
  'beta-glucan':           '"beta-glucan"[tiab] OR "beta-glucans"[tiab]',
  'dhea':                  'DHEA[tiab] OR dehydroepiandrosterone[tiab]',
  'bcaas':                 '"branched-chain amino acid"[tiab] OR "branched-chain amino acids"[tiab] OR BCAA*[tiab]',
  'eaas':                  '"essential amino acids"[tiab]',
  'electrolytes':          'electrolyte*[tiab] AND (hydration[tiab] OR sodium[tiab])',
  'beetroot-extract':      'beetroot[tiab] OR "beet root"[tiab] OR "dietary nitrate"[tiab]',
  'gaba':                  'GABA[tiab] OR "gamma-aminobutyric acid"[tiab]',
  'myo-inositol':          'inositol[tiab]',
  'mucuna-pruriens':       'mucuna[tiab]',
  'glucosamine':           'glucosamine[tiab]',
  'chondroitin':           'chondroitin[tiab]',
  'hyaluronic-acid':       '"hyaluronic acid"[tiab] AND oral[tiab]',
  'iron':                  'iron[tiab]',
  'folate':                'folate[tiab] OR "folic acid"[tiab]',
  'biotin':                'biotin[tiab]',
  'milk-thistle':          'silymarin[tiab] OR "milk thistle"[tiab] OR silibinin[tiab]',
  'elderberry':            'sambucus[tiab] OR elderberry[tiab]',
  'tongkat-ali':           '"eurycoma longifolia"[tiab] OR "tongkat ali"[tiab]',
  'maca-root':             'maca[tiab] OR "lepidium meyenii"[tiab]',
  'vitamin-a':             '"vitamin A"[tiab] OR retinol[tiab]',
  'vitamin-e':             '"vitamin E"[tiab] OR tocopherol*[tiab]',
  'astaxanthin':           'astaxanthin[tiab]',
  'iodine':                'iodine[tiab]',
  'chromium':              'chromium[tiab]',
  'saw-palmetto':          '"saw palmetto"[tiab] OR "serenoa repens"[tiab]',
  'lutein-zeaxanthin':     'lutein[tiab] OR zeaxanthin[tiab]',
};

// Restrict counts to human supplementation research (otherwise "iron" or "calcium" would
// count every chemistry paper ever written).
export const SUPPLEMENTATION_FILTER =
  '(supplement*[tiab] OR "dietary supplements"[mh] OR "administration, oral"[mh]) AND humans[mh]';

export const PUBTYPE_FILTERS = {
  meta_analyses: '(meta-analysis[pt] OR systematic review[pt])',
  rcts:          'randomized controlled trial[pt]',
};
